markdown: kramdown
title: \home\booiljung\hack\hack\blog> $ _
description: S/W | Game | Math | Computer Graphics | Unity | ML | CV 에 대한 기술을 기록하고 공유합니다.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
encoding: utf-8
